### ISSUE TITLE
Kore "benchmark"

### ISSUE THREAD

**Issue by jorisvink** [nanoant/WebFrameworkBenchmark#2]
Hi,

The configuration used for Kore in your benchmarks doesn't seem to indicate a deep understanding of how Kore spreads its workload throughout its worker processes.

In your Kore configuration you set worker_max_connections to 250 and worker_rlimit_nofiles to 1024. It is worth noting that since your test only throws a 100 connections at it Kore is basically running on a single worker (as it attempts to accept() new connections until there is nothing to accept or it has reached its treshold).

I was a bit shocked by the low number at first but the reasoning above explains why.

Honestly, since you've already moved away from the default configuration settings in the config I'd like to suggest you add the following as well:

> worker_accept_treshold 10

Which will spread your 100 test connections across at least 10 worker processes. You can go even further and disable worker affinity so your Linux kernel can actually schedule them on idle CPUs instead of being bound to a single one. You can do that with:

> worker_set_affinity 0

Also worth noting (and this does count for all frameworks you are testing), more workers != better as your CPUs are probably contending with the actual test tool you are using (unless you are sporting 24 CPU cores in which case ignore this).

:-)

.joris

**Comment by jorisvink** [comment]
Poke, it would be lovely if you could rerun the tests with the appropriate options so the workload isn't stuck on a single CPU core :-)

If you want I'll make a small pull request for this.

**Comment by nanoant** [comment]
@jorisvink Yeah, please. PR would be great. I am piled up with other stuff, that's why I couldn't address your issue.

**Comment by jorisvink** [comment]
@nanoant Will do.

**Comment by jorisvink** [comment]
@nanoant  - See PR https://github.com/nanoant/WebFrameworkBenchmark/pull/3

**Comment by nanoant** [comment]
@jorisvink FYI I found some misconfiguration in my workstation that caused some recent benchmarks to underperform. Corrected that and Kore is now no 2. in my benchmark. Very close to no. 1 Java solution.

**Comment by jorisvink** [comment]
@nanoant Very cool, thank you for letting me know!
